/* eslint-disable */
/**
 * @file setupProxy.js
 * @description Create React App development proxy configuration.
 * 
 * @module setupProxy
 * @requires http-proxy-middleware - Express proxy middleware
 * @requires fs - File system for reading port config
 * @requires path - Path utilities
 * 
 * @connections
 * - Used by: Create React App dev server (automatically loaded)
 * - Reads: ../.env.ports for dynamic server port
 * 
 * @summary
 * Configures development server proxy to forward API and WebSocket
 * requests to the backend server. Reads server port from .env.ports
 * file (generated by find-ports.js script) or defaults to 3001.
 * Proxies /api and /socket.io paths.
 */

const { createProxyMiddleware } = require('http-proxy-middleware');
const fs = require('fs');
const path = require('path');

function readServerPort() {
  try {
    const envPath = path.join(__dirname, '..', '..', '.env.ports');
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf8');
      const match = content.match(/SERVER_PORT=(\d+)/);
      if (match && match[1]) return parseInt(match[1], 10);
    }
  } catch (err) {
    // ignore and fall through
  }
  // Default to 3001 if no config found
  return 3001;
}

module.exports = function setupProxy(app) {
  const serverPort = readServerPort();
  const target = `http://localhost:${serverPort}`;


  app.use(
    ['/api', '/socket.io'],
    createProxyMiddleware({
      target,
      changeOrigin: true,
      ws: true,
      logLevel: 'debug',
      onError: (err, req, res) => {
        console.error('Proxy error:', err.message);
        res.status(500).json({ error: 'Proxy error', message: err.message });
      }
    })
  );
};

